title: Encoded Sharing Layers Neural Network (ESL-NN)
description: Hierarchical Multi-Label Classification System based on Pytorch
show_downloads: true
docs_list_title: ACME Documentation
docs:
- title: Introduction
  url: index.md
- title: Download
  url: Download.md
theme: jekyll-theme-slate
