title: Encoded Sharing Layers Neural Network (ESL-NN)
description: Hierarchical Multi-Label Classification System based on Pytorch
show_downloads: true
github:
  zip_url: http://example.com/download.zip
  another_url: www.google.com
theme: jekyll-theme-slate
